include: package:lints/recommended.yaml

linter:
  rules:
    prefer_single_quotes: true
    prefer_relative_imports: false
    always_use_package_imports: true

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
